### PR TITLE
Ok 8 adding and editing reviews for movies - pt 1 (start of redesign) 

### PR DESCRIPTION
**Pull request by DuncanBH**
# Jira Link:

[Jira: https://champlainsaintlambert.atlassian.net/browse/OK-8](https://champlainsaintlambert.atlassian.net/browse/OK-8)

# Context
- Start of work on adding reviews
- Required UI changes, led to applying redesigned color scheme

# Changes
- Changed color scheme
- Refactored some small bootstrap things:
  - Centralized background colors (components -> _app level)
  - Extracted row into MovieList (was Container, might need to be changed later depending on styling on the rest of the pages)
- Changed movie tiles into hover effect 
- Added Review type
- Added review dummy data
- Updated Nav Bar (needs more work - especially for scaling)

# Before and After UI (Required for UI-Impacting PRs) 

Before:
image
image

[After: kzulzg9cd](https://okkoro-kzulzg9cd-okkoro.vercel.app/)
image

### CODE REVIEW

**Review by ClementCadieux — CHANGES_REQUESTED** [review]
"Refactored some small bootstrap things (extracted rows into components, etc)"

Please explain what it is that you did in more details

**Comment by ClementCadieux** [comment]
"Changed movie tiles into hover effect"

I understand why you changed the color scheme as it was a general issue, but it feels like this wasn't related to your story. It's not a massive issue, but let's try to keep focus on our stories when changing designs.

**Comment by dufourmax1738** [comment]
You've added dummy review data inside of the app but do you plan on adding dummy data in the database to work with?

**Comment by DuncanBH** [comment]
> You've added dummy review data inside of the app but do you plan on adding dummy data in the database to work with?
Yes, in the near future when the system is more ready. This current data will also be needed for component testing, eventually.

**Comment by DuncanBH** [comment]
> "Refactored some small bootstrap things (extracted rows into components, etc)"
> 
> Please explain what it is that you did in more details

Done

**Review by ClementCadieux — APPROVED** [review]
Alright, looks good to me!

**Pull request merged**
